#!/bin/sh

case "$1" in 
	 start)
	  echo "Starting the Socket..."
	  start-stop-daemon -S -n SOCKET_SERVER  --exec /usr/bin/aesdsocket -- -d
	  ;;
	 stop)
	  echo "Ending the socket..."
	  start-stop-daemon -K -n SOCKET_SERVER
	  ;;
	  *)
	  echo "Use Start or stop with this Script"
	  exit 1
	  ;;
esac	  
exit 0	  
	   
	  
	 
